from structures import Stack, Queue

stack = Stack()
print("=== Тест Stack ===")
print(f"   Стек: {stack}")
print(f"   Длина: {len(stack)}")
stack.push(10)
stack.push(20)
stack.push(30)
print(f"   После push: {stack}")
print(f"   Длина: {len(stack)}")
print(f"   Верхний элемент: {stack.peek()}")
print(f"   Попытка pop: {stack.pop()}")
print(f"   Стек после pop: {stack}")
print(f"   Длина: {len(stack)}")
print(f"   Пуст ли стек: {stack.is_empty()}")

queue = Queue()
print("\n=== Тест Queue ===")
print(f"   Очередь: {queue}")
print(f"   Длина: {len(queue)}")
queue.enqueue(1)
queue.enqueue(2)
queue.enqueue(3)
print(f"   После enqueue: {queue}")
print(f"   Длина: {len(queue)}")
print(f"   Первый элемент: {queue.peek()}")
print(f"   Попытка dequeue: {queue.dequeue()}")
print(f"   Очередь после dequeue: {queue}")
print(f"   Длина: {len(queue)}")
print(f"   Пустая ли очередь: {queue.is_empty()}")
